version: fastorch
description: a fast pytorch project
time_version: True # if set ture, add time information in version
save_version_files: False # if set true, save each version files in runs
save_version_file_patterns:
  - "*.py"
  - "*.yaml"
pass_dirs:
  - '.'
  - '_'
  - 'runs'
  - 'results'

# filepath
train_dirs:
  - ../data/train_dir
valid_dirs:
  - ../data/valid_dir
test_dirs:
  - ../data/test_dir

cuda: True
# train
random_seed: 42
epochs: 100
batch_size: 128
num_workers: 0
lr: 1e-4
device_ids:
  - 0
valid_every_epochs: 1
early_stop_epochs: -1
start_save_model_epochs: 90
start_scheduler_epoch: 0
save_model_interval_epochs: 1

# test
load_epoch: False # it will test your model if set a value, e.g. best, 10, 100